sonar.projectKey=Ktechnik12_app-server
sonar.organization=ktechnik12

sonar.sources=server
sonar.sourceEncoding=UTF-8

sonar.go.coverage.reportPaths=server/coverage.out

sonar.coverage.exclusions=server/main.go

sonar.exclusions=**/vendor/**,**/bin/**