sonar.projectKey=Ktechnik12_app-server
sonar.organization=ktechnik12

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.go.coverage.reportPaths=server/coverage.out

sonar.exclusions=**/vendor/**,**/bin/**,**/main.go